CREATE PROCEDURE DROP_TABLE(IN schemaName varchar(128), IN tableName varchar(128)) PARAMETER STYLE JAVA MODIFIES SQL DATA LANGUAGE JAVA EXTERNAL NAME 'org.jboss.arquillian.integration.persistence.datasource.derby.DerbyDropTable.dropTable'
CALL DROP_TABLE('app', 'useraccount_audit')
DROP PROCEDURE DROP_TABLE
CREATE TABLE useraccount_audit (ID BIGINT NOT NULL, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), NICKNAME VARCHAR(255), PASSWORD VARCHAR(255), USERNAME VARCHAR(255), OPENDATE DATE, PRIMARY KEY (ID))
