DROP TABLE IF EXISTS useraccount_addres CASCADE;

DROP TABLE IF EXISTS useraccount CASCADE;

DROP TABLE IF EXISTS address CASCADE;

DROP SEQUENCE IF EXISTS hibernate_sequence;


CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS address (
  id          BIGINT       NOT NULL,
  city        VARCHAR(255) NOT NULL,
  houseNumber INTEGER,
  streetName  VARCHAR(255) NOT NULL,
  version     BIGINT,
  zipCode     INTEGER      NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS useraccount (
  id        BIGINT generated BY DEFAULT AS IDENTITY,
  firstname VARCHAR(128) NOT NULL,
  lastname  VARCHAR(128) NOT NULL,
  nickname  VARCHAR(128),
  password  VARCHAR(255) NOT NULL,
  openDate  DATE,
  username  VARCHAR(32)  NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS useraccount_address (
  useraccount_id BIGINT NOT NULL,
  addresses_id   BIGINT NOT NULL,
  PRIMARY KEY (useraccount_id, addresses_id),
  UNIQUE (addresses_id)
);

ALTER TABLE useraccount_address
  ADD CONSTRAINT FK538F4B7EC498202 FOREIGN KEY (useraccount_id) REFERENCES useraccount;

ALTER TABLE useraccount_address
  ADD CONSTRAINT FK538F4B757E57A74 FOREIGN KEY (addresses_id) REFERENCES address;


