drop table if exists useraccount_addres
drop table if exists useraccount
drop table if exists address
drop sequence if exists hibernate_sequence


create table address (id bigint not null, city varchar(255) not null, houseNumber integer, streetName varchar(255) not null, version bigint, zipCode integer not null, primary key (id))
create table useraccount (id bigint generated by default as identity, firstname varchar(128) not null, lastname varchar(128) not null, nickname varchar(128), password varchar(255) not null, openDate date, username varchar(32) not null, primary key (id))
create table useraccount_address (useraccount_id bigint not null, addresses_id bigint not null, primary key (useraccount_id, addresses_id), unique (addresses_id))
alter table useraccount_address add constraint FK538F4B7EC498202 foreign key (useraccount_id) references useraccount
alter table useraccount_address add constraint FK538F4B757E57A74 foreign key (addresses_id) references address
create sequence hibernate_sequence start with 1 increment by 1
