[[cleaning-your-data]]
== Cleaning Your Data

* <<dbunit-cleanup-modes, DBUnit Cleanup Modes>>
* <<using-custom-sql-scripts-for-cleanup, Using Custom SQL Scripts For Cleanup>>

[[dbunit-cleanup-modes]]
=== DBUnit Cleanup Modes

Arquillian Persistence Extension comes with great degree of
configuration. In combination with data sets which you use to seed the
database you can also specify when and how you would like your database
to be cleaned. By default your database is entirely erased before each
test. If you want to control this behavior, use `@Cleanup` annotation
for this purpose. You can define it on the test method level or globally
by decorating test class. Following modes are currently supported:

[[strict]]
==== STRICT

Cleans the entire database. This strategy might require turning off
database constraints (e.g. referential integrity).

[[used_rows_only]]
==== USED_ROWS_ONLY

Deletes only those entries which were defined in data sets used for
seeding.

[[used_tables_only]]
==== USED_TABLES_ONLY

Deletes only those tables which were used in data sets.

You can also specify when you would like to invoke the cleanup
procedure. For instance:

[source,java]
----
@Cleanup(phase = TestExecutionPhase.AFTER, strategy = CleanupStrategy.USED_ROWS_ONLY)
----

You can invoke it `BEFORE` or `AFTER` the test. You can also disable
cleanup by using `TestExecutionPhase.NONE`.

[[using-custom-sql-scripts-for-cleanup]]
=== Using Custom SQL Scripts For Cleanup

You can also use custom SQL scripts to clean your database before or
after the test. For this purpose use `@CleanupUsingScript` annotation
and specifies SQL files which have to be executed. If you don't provide
file names in the annotation itself following rules are applied:

* It's assumed that files are stored in `scripts` folder (or any other
you have configured as default location).
* If annotation is defined on method level, file name has following
format `cleanup-[fully qualified class name]#[test method name].sql`
* If annotation is defined on class level, file name has following
format `cleanup-[fully qualified class name].sql`

The same way as with DBUnit cleanup you can also define test phase when
it should take place.
