ifdef::env-github,env-browser[:outfilesuffix: .adoc]

[[seeding-database]]
== Seeding Database

* <<data-sets, Data Sets>>
** <<flat-xml-data-set, Flat XML Data Set>>
** <<excel-spreadsheets, Excel Spreadsheets>>
** <<yaml-and-json, YAML and JSON>>
* <<schema-creation, Schema Creation>>
* <<custom-sql-scripts, Custom SQL Scripts>>

Creating ad-hoc object graphs in the test code is often too verbose and
makes it harder to read the tests. Arquillian Persistence Extension
provides alternatives to set database fixtures to be used for the given
test.

[[data-sets]]
=== Data Sets

If you are familiar with http://dbunit.sourceforge.net[DBUnit] you already know the
concept of data sets. In brief data sets are files containing rows to be
inserted to the database. In order to seed your database using data set
file put `@UsingDataSet` annotation either on the test itself or on the
class level. If there is definition on both, test level annotation takes
precedence. In addition you can specify files location in the annotation
(default folder is "datasets/". Refer to <<additional-configuration#dbunit-specific-settings,
DBUnit configuration section>> to see how can you customize it). If files are
not specified explicitly, following strategy is applied:

* It's assumed that files are stored in `datasets` folder on classpath
(or any other you have configured as default location).
* If annotation is defined on method level, file name has following
format:
`[fully qualified class name]#[test method name].[default format]`.
* If annotation is defined on class level, file name has following
format: `[fully qualified class name].[default format]`.

Where `default format` is XML, but <<additional-configuration#dbunit-specific-settings, can be also
customized>>.

Arquillian Persistence Extension handles following formats available out
of the box in DBUnit:

[[flat-xml-data-set]]
==== Flat XML Data Set

Simple XML format where each element represents rows in the given table
and attributes names corresponds to its columns. You can also explicitly
set `null` value for the given column, by simply using `[null]` keyword,
as illustrated below.

Flat XML Data Set

[source,xml]
----
<dataset>
    <useraccount id="1" firstname="Clark" lastname="Kent" username="ckent" password="LexLuthor123" nickname="[null]" />
</dataset>
----

[[excel-spreadsheets]]
==== Excel Spreadsheets

Another format supported out of the box by DBUnit. In order to use it
follow these conventions:

* Each table should have dedicated sheet within the Excel file.
* First row should contain column labels.

Have a look at the
https://github.com/arquillian/arquillian-extension-persistence/blob/master/int-tests/src/test/resources-datasets/datasets/single-user.xls[example].

[[yaml-and-json]]
==== YAML and JSON

In addition to the format supported out of the box by DBUnit, Arquillian
Persistence Extension provides alternative way to describe your data
sets either by using YAML or JSON. Those formats are a bit more readable
for the human (and for machines too!). So instead of hand-crafting XML
or Excel files you can do define your data sets in
http://en.wikipedia.org/wiki/YAML[YAML]:

Data set described in YAML

[source,java]
----
useraccount:
  - id: 1
    firstname: Clark
    lastname: Kent
    username: ckent
    password: LexLuthor123
    nickname: "[null]"
----

or in http://en.wikipedia.org/wiki/JavaScript_Object_Notation[JSON]:

Data set described in JSON

[source,java]
----
{
  "useraccount":
  [
    {
      "id": "1",
      "firstname" : "Clark",
      "lastname" : "Kent",
      "username" : "ckent",
      "password" : "LexLuthor123",
      "nickname" : "[NULL]"
    }
  ]
}
----

[[section]]

[[schema-creation]]
=== Schema Creation

If you want to use custom SQL scripts for schema creation you can
decorate your test using `@CreateSchema` annotation providing list of
scripts you want to execute before test class. They will be executed
only once. By convention such scripts will be first looked in *schema*
folder, but you can also provide full path if you wish.

[[custom-sql-scripts]]
=== Custom SQL Scripts

If you want you can also use seed your database using plain SQL (or
execute any other action directly on the database level). To achieve it
simply put `@ApplyScriptBefore` or `@ApplyScriptAfter` annotation either
directly on your test method or on the test class. Scripts will be
executed before or after test method accordingly. If there is definition
on both, test level annotation takes precedence.

By convention Arquillian Persistence Extension will look for these
scripts in the **scripts** folder (in a Maven project, that's typically
`src/test/resources/scripts` in the source tree), but you can customize
it as you wish - see <<additional-configuration#general-settings, configuration
section>> how to do it. You can also specify files location in the
annotation, the same way as you can do with DBUnit data sets. If files
are not specified explicitly, following strategy is applied:

* It's assumed that files are stored in `scripts` folder (or any other
you have configured as default location).
* If annotation is defined on method level, file name has following
format:
`[before|after]-[fully qualified class name]#[test method name].sql`.
* If annotation is defined on class level, file name has following
format: `[before|after]-[fully qualified class name].sql`.
